import type { Metadata } from "next";
import type { Viewport } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./(components)/Providers";
import Nav from "./(components)/Nav"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport : Viewport = {
  width: "device-width",
  initialScale: 1,
  height: "device-height",
  maximumScale: 1,
  userScalable: false,
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col m-0 p-0 breathing">
        <Providers> 
          <Nav/>
            <main className="w-full md:pl-[72px]">
              {children}
            </main>
        </Providers>
      </body>
    </html>
  );
}``
